export const travelData = [
  {
    id: 2,
    name: "Emirates Airline",
    logo: "src/assets/images/emirates.png",
    flight_detail: {
      flight_features: {
        cabin: 1,
        baggage: "40KGs",
        usb_power: true,
        free_meal: true,
        wifi: true,
        entertainment: true,
      },
      flight_number: "EK 1234",
      flight_bus: "Airbus A380",
      flight_class: "Economy class",
      start_time: "10:45 AM",
      start_date: "Mon, 16 June 2025",
      end_time: "02:00 PM",
      end_date: "Mon, 16 June 2025",
      seats_layout: "2-2-2",
      upgradable: true,
    },
    airport_details: {
      startAirport: "Dubai International Airport (DXB)",
      startTerminal: "Terminal 3 International",
      endAirport:
        "Chhatrapati Shivaji Maharaj International Airport Mumbai (BOM)",
      endTerminal: "Terminal 1 international",
    },
    stop: [],
    price: {
      economyLite: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "",
        seatSelection: "Assigned at check-in",
        Changes: "with very high fee",
        Refundable: "",
        price: "48",
      },
      economyStandard: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "01 item (up to 20kg)",
        seatSelection: "Standard (free)",
        Changes: "$4 + fare difference",
        Refundable: "",
        price: "52",
      },
      economyFlex: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "02 items (up to 20kg each)",
        seatSelection: "Any (free, including preferred seats)",
        Changes: "Free (fare differences may apply)",
        Refundable: "with a small fee",
        price: "66",
      },
    },
  },
  {
    id: 3,
    name: "Qatar Airways",
    logo: "src/assets/images/qatar.png",
    flight_detail: {
      flight_features: {
        cabin: 1,
        baggage: "40KGs",
        usb_power: true,
        free_meal: true,
        wifi: true,
        entertainment: true,
      },
      flight_number: "QR 5678",
      flight_bus: "Airbus A320",

      flight_class: "Business class",
      start_time: "10:45 AM",
      start_date: "Mon, 16 June 2025",
      end_time: "02:00 PM",
      end_date: "Mon, 16 June 2025",
      seats_layout: "1-1-1",
      upgradable: true,
    },
    airport_details: {
      startAirport: "Dubai International Airport (DXB)",
      startTerminal: "Terminal 3 International",
      endAirport:
        "Chhatrapati Shivaji Maharaj International Airport Mumbai (BOM)",
      endTerminal: "Terminal 1 international",
    },
    stop: [
      {
        name: "Doha (DOH)",
        stayTime: "01h 15min",
        stayStartingtime: "",
        stayEndingtime: "",
      },
      {
        name: "Demo (DOH)",
        stayTime: "01h 15min",
        stayStartingtime: "",
        stayEndingtime: "",
      },
    ],
    price: {
      economyLite: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "",
        seatSelection: "Assigned at check-in",
        Changes: "with very high fee",
        Refundable: "",
        price: "70",
      },
      economyStandard: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "01 item (up to 20kg)",
        seatSelection: "Standard (free)",
        Changes: "$4 + fare difference",
        Refundable: "",
        price: "120",
      },
      economyFlex: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "02 items (up to 20kg each)",
        seatSelection: "Any (free, including preferred seats)",
        Changes: "Free (fare differences may apply)",
        Refundable: "with a small fee",
        price: "150",
      },
    },
  },
  {
    id: 1,
    name: "Flydubai",
    logo: "src/assets/images/flydubai_icon.jpeg",
    airport_details: {
      startAirport: "Dubai International Airport (DXB)",
      startTerminal: "Terminal 3 International",
      endAirport:
        "Chhatrapati Shivaji Maharaj International Airport Mumbai (BOM)",
      endTerminal: "Terminal 1 international",
    },
    flight_detail: {
      flight_features: {
        cabin: 1,
        baggage: "40KGs",
        usb_power: true,
        free_meal: true,
        wifi: true,
        entertainment: true,
      },
      flight_bus: "Airbus A120",
      flight_number: "BA 9101",
      flight_class: "First class",
      start_time: "10:45 AM",
      start_date: "Mon, 16 June 2025",
      end_time: "02:00 PM",
      end_date: "Mon, 16 June 2025",
      seats_layout: "1-1-1-1",
      upgradable: true,
    },
    stop: [
      {
        name: "Doha (DOH)",
        stayTime: "01h 15min",
        stayStartingtime: "",
        stayEndingtime: "",
      },
    ],
    price: {
      economyLite: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "",
        seatSelection: "Assigned at check-in",
        Changes: "with very high fee",
        Refundable: "",
        price: "40",
      },
      economyStandard: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "01 item (up to 20kg)",
        seatSelection: "Standard (free)",
        Changes: "$4 + fare difference",
        Refundable: "",
        price: "80",
      },
      economyFlex: {
        presonalItem: "01 item (e.g., small backpack, laptop bag)",
        baggage: "02 items (up to 20kg each)",
        seatSelection: "Any (free, including preferred seats)",
        Changes: "Free (fare differences may apply)",
        Refundable: "with a small fee",
        price: "110",
      },
    },
  },
];

export const passengersOptions = [
  { value: "01", label: "01" },
  { value: "02", label: "02" },
  { value: "03", label: "03" },
  { value: "04", label: "04" },
  { value: "05", label: "05" },
  { value: "06", label: "06" },
  { value: "07", label: "07" },
  { value: "08", label: "08" },
  { value: "09", label: "09" },
  { value: "10", label: "10" },
];
export const cabinClass = [
  { value: "economy", label: "Economy" },
  { value: "businessClass", label: "Business Class" },
  { value: "firstClass", label: "First Class" },
];
